# Generated by Django 4.1.1 on 2022-10-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_autor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="livro",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
    ]
